services:
  make:
    image: mkuf/klipper:${TAG:-latest}-mcu
    tty: true
    privileged: true
    entrypoint: make
    working_dir: /opt/klipper
    volumes:
      - ./config/build.config:/opt/klipper/.config
      - ./out:/opt/klipper/out
